### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by Gnork** [curious-containers/curious-containers#49] opened 2019-09-03 13:48 UTC
Details will be discussed later.

**Comment by Bluemi** [comment] 2020-01-17 09:15
Possible Features:
- Rest Endpoint for User Management
  - create User
  - block User
  - change pw (with password limitations (minimum length))
- quotas
  - ram quota
  - gpu quota
  - on request...

**Comment by Domprobst** [comment] 2023-06-26 12:42
Duplicate of #118

**Closed by Domprobst** 2023-06-26 12:42 UTC
Labels: enhancement, cc-agency
